### ISSUE TITLE
New standard_name: mass_concentration_of_diazotrophs_expressed_as_carbon_in_sea_water

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#24] opened 2020-01-13 14:05 UTC
**Proposer's name** Ute Daewel / Beate Geyer
**Date** Wed Jul 19 06:43:37 MDT 2017

**- Term** mass_concentration_of_diazotrophs_expressed_as_carbon_in_sea_water
**- Definition** 'Mass concentration' means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as 'nitrogen' or a phrase such as 'nox_expressed_as_nitrogen'.The phrase 'expressed_as' is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A. In ocean modelling, diazotrophs are phytoplankton of the phylum cyanobacteria distinct from other phytoplankton groups in their ability to fix nitrogen gas in addition to nitrate and ammonium. Phytoplankton are autotrophic prokaryotic or eukaryotic organisms that live near the water surface where there is sufficient light to support photosynthesis.
**- Units** kg m-3

The proposal was sent to the mailling list in 2017.
mole_concentration_of_diazotrophs_expressed_as_carbon_in_sea_water already exists, but we want to use the mass_concentration as it exists for other species (e.g., diatoms and flagellates).

**Comment by roy-lowry** [comment] 2020-01-13 14:43
As we now have handling biological species as co-ordinates rather than as Standard Name objects accepted into CF I would appreciate it if the definition here - and in other similar Standard Names - doesn't explicitly mention 'biological species' as this is now wrong. I would suggest replacing 'biological species' by something like 'biological groups'

One could question whether this (and the similar zooplankton request) should be accepted on the grounds that zooplankton and diazotrophs should be co-ordinates. However, I think the arguments of precedent (several zooplankton-based Standard Names already exist) and that diazotrophs and zooplankton are trophic groups rather than taxa are strong enough to counter rejection. To reinforce this I would also remove the mapping of diazatroph to Cyanobacteria from the definition.

**Comment by GeyerB** [comment] 2020-01-17 13:18
The given definition was taken from the existing definitions of mole_concentration_of_diazotrophs_expressed_as_carbon_in_sea_water and net_primary_mole_productivity_of_biomass_expressed_as_carbon_by_diazotrophs
We could rephrase 'A chemical or biological species denoted by X may be described' to 'A chemical species or biological group denoted by X may be described' in **all** definitions.

The already existing standard_names for diazotrophs refer to the representation of cyanobacteria in models, so that the mapping of diazotrophs to cyanobacteria remains necessary. Alternatively we would suggest to rename all of the related standard_names from diazotrophs to cyanobacteria to allow for standard_names that address diazotrophs including also non-cyanobacterial groups.

**Comment by roy-lowry** [comment] 2020-01-17 14:35
My intention was to replace 'biological species' by 'biological groups'  in all existing definitions so that would be a most welcome change.

My intention is to minimise any linkage between existing Standard Names and biological taxa to smooth the transition to taxa as co-ordinates in CF. Ideally, the proposal to do this would have been incorporated into CF before any Standard Names for specific biological entities had been set up. I tried to do this back in 2012 but getting Trac ticket 99 through took longer then expected. To date, not too much damage has been done because the biological Standard Names are confined to model outputs with only a handful of parameters per file. What I really wanted to address was making datasets with measured parameters for tens or hundreds of taxa more interoperable with formats like Darwin Core or the SeaDataNet Biological Data Format.

What I was requesting was the removal the taxonomic label Cyanobacteria (a Phylum) from your definition that could then be extended to existing definitions if an appropriate form of words could be agreed. My suggestion would be to replace:

In ocean modelling, diazotrophs are phytoplankton of the phylum cyanobacteria distinct from other phytoplankton groups in their ability to fix nitrogen gas in addition to nitrate and ammonium.

by

In ocean modelling, diazotrophs are phytoplankton that are able to fix nitrogen gas in addition to nitrate and ammonium.

Would this be acceptable? If not, then things are no worse for me than they were before this proposal. However, please do NOT replace diazotroph by Cyanobacteria in the Standard Names as that would be a big step backwards for what I am trying to achieve.

**Comment by davidhassell** [comment] 2020-01-17 15:04
Just for the record, the Taxon Names and Identifiers enhancement mentioned by @roy-lowry (https://github.com/cf-convention/cf-conventions/issues/218 and Trac ticket 99) has now been accepted and will appear in CF-1.8

**Comment by japamment** [comment] 2020-01-22 17:37
Dear Ute and Beate,

Thanks for this proposal. I have indeed found the original email from 2017 in the mailing list archives - many apologies that it seems to have been overlooked at the time: [http://mailman.cgd.ucar.edu/pipermail/cf-metadata/2017/009409.html](http://mailman.cgd.ucar.edu/pipermail/cf-metadata/2017/009409.html).

Certainly we do have existing names for diazotrophs and had this proposal been processed in 2017 (as it should have been) I'm sure we would have agreed to it at the time. I do want to find a way forward so that we can add this name without unnecessary further delay. However, as has already been pointed out, we need to be consistent with the new biological taxon standard names [cf-convention/discuss#27](cf-convention/discuss#27). Reading through Roy's and Beate's comments I can see two possible ways forward with this particular proposal.

The first is to follow Roy's argument that diazotrophs are a trophic rather than a taxonomic group. I am not a biologist so I had to look up what "trophic" means! (Apparently it's a grouping of organisms in a particular part of the food web, rather than a grouping by species, phylum, etc.). Then we could add the name as proposed and use Roy's definition:
**mass_concentration_of_diazotrophs_expressed_as_carbon_in_sea_water** (kg m-3).
' "Mass concentration" means mass per unit volume and is used in the construction "mass_concentration_of_X_in_Y", where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A. In ocean modelling, diazotrophs are phytoplankton that are able to fix nitrogen gas in addition to nitrate and ammonium. Phytoplankton are autotrophic prokaryotic or eukaryotic organisms that live near the water surface where there is sufficient light to support photosynthesis.'

As a general point I agree with the suggestion to replace "chemical or biological species" in the definitions of standard names for mass|mole_fraction|concentration with "chemical species or biological group". (This will also require the definitions of 608 existing names to be updated, but I will open a separate issue for that).

If Ute and Beate are happy with removing the mention of cyanobacteria from the definition of the proposed name then I think we can accept it in this form.

However, Beate commented that "The already existing standard_names for diazotrophs refer to the representation of cyanobacteria in models, so that the mapping of diazotrophs to cyanobacteria remains necessary. Alternatively we would suggest to rename all of the related standard_names from diazotrophs to cyanobacteria to allow for standard_names that address diazotrophs including also non-cyanobacterial groups." I'm a little confused by this remark - are you saying that "diazotrophs" is the term used by ocean modellers to mean "cyanobacteria"? Again, my biological knowledge is somewhat limited but my understanding is that, in general, cyanobacteria are a type of organism classed as diazotrophs, but other types of organism can also be classed as diazotrophs so in fact it's a wider grouping.

If the proposed (and existing) names really are restricted to meaning only cyanobacteria, then we should use the new taxon names. The proposed quantity would then be (as discussed in [cf-convention/discuss#27](cf-convention/discuss#27):
**mass_concentration_of_biological_taxon_expressed_as_carbon_in_sea_water** (kg m-3)
' "Mass concentration" means mass per unit volume and is used in the construction "mass_concentration_of_X_in_Y", where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as"nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction "A_expressed_as_B", where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A. Mass concentration of biota expressed as carbon is also referred to as "carbon biomass". "Biological taxon" is a name or other label identifying an organism or a group of organisms as belonging to a unit of classification in a hierarchical taxonomy. There must be an auxiliary coordinate variable with standard name biological_taxon_name to identify the taxon in human readable format and optionally an auxiliary coordinate variable with standard name biological_taxon_identifier to provide a machine-readable identifier. See Section 6.1.2 of the CF convention (version 1.8 or later) for information about biological taxon auxiliary coordinate variables.'

This would need to be accompanied by a scalar coordinate variable with standard name biological_taxon_name whose value would be "cyanobacteria" and optionally a biological_taxon_identifier coordinate variable giving the appropriate identifier.

I think the choice between these two approaches really hinges on what is meant by "diazotroph" in the proposed and existing names. If we adopt the second approach we should also do the same for existing names which would mean turning them into aliases of taxon names.

Further comments on this issue would be most welcome!

Best wishes,
Alison

**Comment by udaewel** [comment] 2020-02-03 07:33
Dear Alison,

thanks a lot for structuring the problem clearly. In deed the difficulty arises with the specification "in ocean modelling ... " since in ocean modelling only cyanobacteria are considered. By removing the word "cyanobacteria" the sentence doesn't really make sense anymore. 

Therefore I agree that it makes most sense to use the new taxon names (mass_concentration_of_biological_taxon_expressed_as_carbon_in_sea_water (kg m-3)) for cyanobacteria. That would then especially cover for what is represented in ocean modelling.

The other standard name (mass_concentration_of_diazotrophs_expressed_as_carbon_in_sea_water (kg m-3)) is however also neccessary for actually addressing diazotrophs as a group, but then the sentence that refers to ocean modelling and cyanobacteria should be removed altogether.

Best wishes,
Ute

**Comment by japamment** [comment] 2020-02-24 15:19
Dear Ute,

Many thanks for your reply. I think we are now agreed to use the existing name mass_concentration_of_biological_taxon_expressed_as_carbon_in_sea_water, accompanied by a coordinate variable with standard name biological_taxon_name and value "cyanobacteria", to represent the quantity you were originally requesting in this proposal. We will therefore not add the standard name mass_concentration_of_diazotrophs_expressed_as_carbon_in_sea_water.

This discussion has highlighted the fact that the definitions of the existing diazotroph names (seven of them) focus on cyanobacteria rather than other types of diazotroph. The definitions refer to ocean modelling because I think all the diazotroph names were originally introduced for CMIP5/CMIP6. I don't know if the names have ever been used to describe observations.

@roy-lowry has expressed the strong view that we shouldn't change the existing names to say 'cyanobacteria' instead of 'diazotroph' as this would be a backwards move given that we have just created the generic taxon names. I agree.

Ute raised the point that we may at some stage need names that refer to all diazotrophs rather than concentrating only on cyanobacteria. Although such names are not being requested at the moment, and although it is CF practice not to add new names unless there is a clear need for them, I think we do need to allow for this possibility while at the same time avoiding confusion with the existing names.

I propose the following to resolve this issue.

The 7 existing diazotroph names are:
growth_limitation_of_diazotrophs_due_to_solar_irradiance;
iron_growth_limitation_of_diazotrophs;
mass_concentration_of_diazotrophs_expressed_as_chlorophyll_in_sea_water;
mole_concentration_of_diazotrophs_expressed_as_carbon_in_sea_water;
net_primary_mole_productivity_of_biomass_expressed_as_carbon_by_diazotrophs;
nitrogen_growth_limitation_of_diazotrophs;
tendency_of_mole_concentration_of_particulate_organic_matter_expressed_as_carbon_in_sea_water_due_to_net_primary_production_by_diazotrophs

1) We should deprecate the use of the existing names by adding the following text to all their definitions:
'The use of this standard name to describe cyanobacteria populations is deprecated. Instead, use the generic taxon name X accompanied by a coordinate variable with standard name 'biological_taxon_name' and a value of 'cyanobacteria'. (Here, 'X' would be replaced by the appropriate generic name, e.g., the definition of iron_growth_limitation_of_diazotrophs would direct the user to the name iron_growth_limitation_of_biological_taxon.) There is precedent for adding advice of this type to standard name definitions, see for example precipitation_flux_onto_canopy and surface_downward_mole_flux_of_carbon_dioxide.

2) To facilitate (1) we should introduce new biological_taxon names as follows:

**growth_limitation_of_biological_taxon_due_to_solar_irradiance** (Canonical units: 1)
' "Growth limitation due to solar irradiance" means the ratio of the growth rate of a species population in the environment (where the amount of sunlight reaching a location may be limited) to the theoretical growth rate if there were no such limit on solar irradiance. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. "Irradiance" means the power per unit area (called radiative flux in other standard names), the area being normal to the direction of flow of the radiant energy. Solar irradiance is essential to the photosynthesis reaction and its presence promotes the growth of phytoplankton populations. "Biological taxon" is a name or other label identifying an organism or a group of organisms as belonging to a unit of classification in a hierarchical taxonomy. There must be an auxiliary coordinate variable with standard name biological_taxon_name to identify the taxon in human readable format and optionally an auxiliary coordinate variable with standard name biological_taxon_identifier to provide a machine-readable identifier. See Section 6.1.2 of the CF convention (version 1.8 or later) for information about biological taxon auxiliary coordinate variables.'

**iron_growth_limitation_of_biological_taxon** (Canonical units: 1)
' "Iron growth limitation" means the ratio of the growth rate of a species population in the environment (where there is a finite availability of iron) to the theoretical growth rate if there were no such limit on iron availability. "Biological taxon" is a name or other label identifying an organism or a group of organisms as belonging to a unit of classification in a hierarchical taxonomy. There must be an auxiliary coordinate variable with standard name biological_taxon_name to identify the taxon in human readable format and optionally an auxiliary coordinate variable with standard name biological_taxon_identifier to provide a machine-readable identifier. See Section 6.1.2 of the CF convention (version 1.8 or later) for information about biological taxon auxiliary coordinate variables.'

**net_primary_mole_productivity_of_biomass_expressed_as_carbon_by_biological_taxon** (Canonical units: mol m-2 s-1)
' "Production of carbon" means the production of biomass expressed as the mass of carbon which it contains. Net primary production is the excess of gross primary production (rate of synthesis of biomass from inorganic precursors) by autotrophs ("producers"), for example, photosynthesis in plants or phytoplankton, over the rate at which the autotrophs themselves respire some of this biomass. "Productivity" means production per unit area. The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A. "Biological taxon" is a name or other label identifying an organism or a group of organisms as belonging to a unit of classification in a hierarchical taxonomy. There must be an auxiliary coordinate variable with standard name biological_taxon_name to identify the taxon in human readable format and optionally an auxiliary coordinate variable with standard name biological_taxon_identifier to provide a machine-readable identifier. See Section 6.1.2 of the CF convention (version 1.8 or later) for information about biological taxon auxiliary coordinate variables.'

**nitrogen_growth_limitation_of_biological_taxon** (Canonical units: 1)
' "Nitrogen growth limitation" means the ratio of the growth rate of a species population in the environment (where there is a finite availability of nitrogen) to the theoretical growth rate if there were no such limit on nitrogen availability. "Biological taxon" is a name or other label identifying an organism or a group of organisms as belonging to a unit of classification in a hierarchical taxonomy. There must be an auxiliary coordinate variable with standard name biological_taxon_name to identify the taxon in human readable format and optionally an auxiliary coordinate variable with standard name biological_taxon_identifier to provide a machine-readable identifier. See Section 6.1.2 of the CF convention (version 1.8 or later) for information about biological taxon auxiliary coordinate variables.'

**tendency_of_mole_concentration_of_particulate_organic_matter_expressed_as_carbon_in_sea_water_due_to_net_primary_production_by_biological_taxon** (Canonical units: mol m-3 s-1)
'The phrase "tendency_of_X" means derivative of X with respect to time. "Mole concentration" means number of moles per unit volume, also called "molarity", and is used in the construction "mole_concentration_of_X_in_Y", where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. "Production of carbon" means the production of biomass expressed as the mass of carbon which it contains. Net primary production is the excess of gross primary production (the rate of synthesis of biomass from inorganic precursors) by autotrophs
("producers"), for example, photosynthesis in plants or phytoplankton, over the rate at which the autotrophs themselves respire some of this biomass. In the oceans, carbon production per unit volume is often found at a number of depths at a given horizontal location. That quantity can then be integrated to calculate production per unit area at the location. Standard names for production per unit area use the term "productivity". "Biological taxon" is a name or other label identifying an organism or a group of organisms as belonging to a unit of classification in a hierarchical taxonomy. There must be an auxiliary coordinate variable with standard name biological_taxon_name to identify the taxon in human readable format and optionally an auxiliary coordinate variable with standard name biological_taxon_identifier to provide a machine-readable identifier. See Section 6.1.2 of the CF convention (version 1.8 or later) for information about biological taxon auxiliary coordinate variables.'

(We already have standard names for mass_concentration_of_biological_taxon_expressed_as_chlorophyll_in_sea_water and mole_concentration_of_biological_taxon_expressed_as_carbon_in_sea_water.)

3) We should retain the existing diazotroph names as distinct entries in the standard name table (i.e. not turn them into aliases of the new taxon names). The new names are too generic to be exact synonyms of the existing ones. Also, data written with the existing names , e.g. CMIP6 data, would not carry the necessary coordinate variable to identify the taxon. As ever, we need to be careful not to invalidate existing data.

4) If in future we do require names for all diazotrophs, we will need to distinguish them clearly from our previous use of 'diazotroph' to mean 'cyanobacteria'. We do not need to agree an exact phrase at this point in time, but one possibility would be simply to say 'diazotroph_groups', for example, iron_growth_limitation_of_diazotroph_groups, and supply appropriate definition text to disambiguate this from the older term.

Comments on this proposal would be most welcome.

Best wishes,
Alison

**Comment by roy-lowry** [comment] 2020-02-24 16:50
@japamment I think we're in danger of converting a molehill into a mountain here and I worry about my being the cause of restructuring of existing data sets to address a comparatively trivial semantic issue. Don't forget that as well as adopting generic Standard Names in place of taxon-specific names implementation of 'Trac99' requires the addition of a 'taxon' co-ordinate (a dimension) to hold the taxon labels.

I am a strong believer in backward compatability and so would be more comfortable a simpler, less destructive solution. So, I think it might be worth one more attempt to find a mutually-agreeable replacement for the phrase 'diazotrophs are phytoplankton of the phylum cyanobacteria distinct from other phytoplankton groups in their ability to fix nitrogen gas in addition to nitrate and ammonium.' My objection to this is that it makes 'Cyanobacteria' and diazatroph' synonymous, turning 'diazatroph' into taxonomic label. Even if all diazatrophs were Cyanobacteria (there are other taxa in plankton such as Archaeas), I would consider such a semantic connection to be unwise - it's like saying chalk is synonymous with cheese.

Would changing the phrasing in existing and new diazatroph Standard Name definitions to 'diazotrophs are phytoplankton (predominantly from Phylum Cyanabacteria) that are able to fix nitrogen gas in addition to nitrate and ammonium.' be acceptable to @GeyerB and @udaewel ? If so, we have a painless solution.

**Comment by martinjuckes** [comment] 2020-02-25 14:20
I like the approach that Roy is suggesting, but I have the impression that "diazotroph" outside CF can be any microorganism, on land or at sea, and the terms we have here are intended to be restricted to microorganisms living in the oceans ("diazotrophic plankton" perhaps?). `diazotrophs` is used in groups of names which cover different categories of phytoplankton (calcerous phytoplakton, diatoms, diazotrophs, picophytoplankton, miscellaneous phytoplankton).

As the number of "trophs" we need to deal with in the CF convention is fairly limited, I think we are better having explicit definitions imported into registered standard names, rather than using the taxon semantics.

I suggest replacing `_diazotrophs_` in existing standard names with `_diazotrophic_phytoplankton_`.

Based on a brief piece of online research, I raise the following text for discussion: '**diazotrophic phytoplankton are phytoplankton (predominantly from Phylum Cyanabacteria) that are able to fix molecular nitrogen (gas or solute) and grow without additional sources of nitrogen**'. This differs from Roy's text in a couple of places:
- replacing "nitrogen gas" with "molecular nitrogen (gas or solute)", because the key issue appears to be the ability to use N2;
- changing the end of the statement to "and grow without additional sources of nitrogen": this restricts the group to organisms which can survive on their fixed nitrogen, and excludes those that can only supplement their nitrogen supply through fixation. Is this accurate?

**Comment by roy-lowry** [comment] 2020-02-25 18:18
Just spent an hour composing an answer but it seems to have got lost in a GitHub server error - Grrrrrr!

So trying again....

I like the idea of replacing diazotrophs with diazotrophic_phytoplankton. There are many out of scope diazotrophs that are best explicitly excluded. These are not just microorganisms - legumes like peas and broad beans can be considered as diazotrophs.

I'm less comfortable with the last bit of the modified definition as it doesn't sit comfortably in my view of the natural environment - it's not easy to measure for a given taxon and growing organisms excrete nitrogen.

Could we roll back to 'diazotrophic phytoplankton are phytoplankton (predominantly from Phylum Cyanabacteria) that are able to fix molecular nitrogen (gas or solute) in addition to nitrate and ammonium.'?

Note that most Cyanobacteria genera, including the extremely abundant Prochlorococcus and Synechococcus, are not diazotrophic.

**Comment by martinjuckes** [comment] 2020-02-26 08:36
Hi Roy,

thanks for making the effort to get those views across. I'm happy to accept the wording in your [last post](https://github.com/cf-convention/discuss/issues/24#issuecomment-590994114) (my previous wording gave too much weight to an outlying interpretation of what constitutes a diazotroph),

regards,
Martin

**Comment by japamment** [comment] 2020-02-27 17:33
Dear Roy and Martin,

Many thanks to you both for taking the time to contribute to this discussion and for coming up with the suggestion of 'diazotrophic_phytoplankton'. I am certainly happy to go for this solution if it is acceptable to everyone as it does keep things much simpler. I am pleased that the new definition is making a much clearer distinction between 'diazotroph' and 'cyanobacteria', which was at the root of the original problem.

In the light of this discussion, it seems that we could accept a slightly modified version of Ute's original proposal:
**mass_concentration_of_diazotrophic_phytoplankton_expressed_as_carbon_in_sea_water** (kg m-3)
' "Mass concentration" means mass per unit volume and is used in the construction "mass_concentration_of_X_in_Y", where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A. Phytoplankton are algae that grow where there is sufficient light to support photosynthesis. Diazotrophic phytoplankton are phytoplankton (predominantly from Phylum Cyanobacteria) that are able to fix molecular nitrogen (gas or solute) in addition to nitrate and ammonium.'

We would then also modify the definitions of the seven existing names to be consistent with this.

@udaewel, @GeyerB, would this solution be acceptable to you?

Best wishes,
Alison

**Comment by udaewel** [comment] 2020-02-28 17:03
Dear Alison and all,

we actually think that this is a very good solution to the problem and would support this. 

Best wishes,
Ute and Beate

**Comment by japamment** [comment] 2020-03-02 15:31
Dear Ute, Beate, Roy and Martin,

Excellent! It seems we are all now agreed on this issue. The new diazotrophic_phytoplankton name is accepted for publication in the standard name table. Aliases will be created for the existing diazotroph names to change them to also say diazotrophic_plankton. These changes can all be viewed in the [CEDA vocabulary editor](http://cfeditor.ceda.ac.uk/proposals/1?status=accepted&namefilter=diazotroph&proposerfilter=&descfilter=&unitfilter=&yearfilter=&commentfilter=&filter+and+display=Filter) and they will be published in the 9th March standard names update.

Many thanks to everyone for persevering with this issue and bringing it to consensus.

Best wishes,
Alison

**Comment by feggleton** [comment] 2020-03-10 16:35
These changes have been published in version 72 of the standard name table.

**Closed by feggleton** 2020-03-10 16:35 UTC
Labels: standard name
